before_script:
  - npm rebuild node-sass
  - yarn install

stages:
  - deploy

deployment:
  stage: deploy
  script:
    - yarn build
    - rm -r /var/www/public/dashboard
    - cp -r ./build /var/www/public/dashboard
    - cp -f ./htaccess_dev /var/www/public/dashboard/.htaccess
  only:
    - develop
    
